In [13]:
import numpy as np
import matplotlib.pyplot as plt
import sys

sys.path.append('../src/')
from algorithms.flood_filling import flood_fill4_rec, flood_fill4_iter


In [14]:
image = np.array([
    [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
    [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
    [0, 0, 4, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
    [0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 
    [0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
    [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
    [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
    [0, 3, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
    [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
    [0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
])

In [15]:
print(image)

[[1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 4 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 1 2 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 3 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [16]:
flood_fill4_iter(image, 7, 7, 0, 9)
print(image)

[[1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 4 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 1 2 9 9 9 9 9 9 9 9 9]
 [0 0 0 0 1 9 9 9 9 9 9 9 9 9 9]
 [0 0 0 0 1 9 9 9 9 9 9 9 9 9 9]
 [0 3 0 0 1 9 9 9 9 9 9 9 9 9 9]
 [0 0 0 0 1 9 9 9 9 9 9 9 9 9 9]
 [0 0 0 0 1 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [17]:
flood_fill4_rec(image, 0, 0, 1, 8)
print(image)

[[8 8 8 8 8 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 8 0 0 0 0 0 0 0 0 0 0]
 [0 0 4 0 8 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 8 8 8 8 8 8 8 8 8 8 8]
 [0 0 0 0 8 2 9 9 9 9 9 9 9 9 9]
 [0 0 0 0 8 9 9 9 9 9 9 9 9 9 9]
 [0 0 0 0 8 9 9 9 9 9 9 9 9 9 9]
 [0 3 0 0 8 9 9 9 9 9 9 9 9 9 9]
 [0 0 0 0 8 9 9 9 9 9 9 9 9 9 9]
 [0 0 0 0 8 8 8 8 8 8 8 8 8 8 8]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
